"""
Lumina Life OS — Insight Models
Author: Burak Kaygusuzoglu <bkaygusuzoglu@hotmail.com>
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, ConfigDict


class InsightType(str, Enum):
    """Classification of an AI-generated insight.

    - ``weekly_report``    → Sunday evening life summary
    - ``mood_pattern``     → Detected emotional trend
    - ``productivity``     → Task completion pattern
    - ``sleep_quality``    → Sleep trend analysis
    - ``growth``           → Personal development observation
    - ``alert``            → Actionable warning (e.g. burnout risk)
    - ``greeting``         → Daily personalised greeting (cached 1 h)
    """

    WEEKLY_REPORT = "weekly_report"
    MOOD_PATTERN = "mood_pattern"
    PRODUCTIVITY = "productivity"
    SLEEP_QUALITY = "sleep_quality"
    GROWTH = "growth"
    ALERT = "alert"
    GREETING = "greeting"


class InsightResponse(BaseModel):
    """A single AI-generated insight persisted in the database.

    Attributes:
        id: UUID primary key.
        user_id: Owner's UUID.
        insight_type: Category of the insight.
        title: Short headline.
        content: Full AI-generated narrative (Markdown).
        data_snapshot: Raw aggregated data used when generating.
        generated_at: When Claude produced this insight.
    """

    model_config = ConfigDict(from_attributes=True)

    id: str
    user_id: str
    insight_type: InsightType
    title: str
    content: str
    data_snapshot: dict = {}
    generated_at: datetime


class WeeklyReport(BaseModel):
    """Structured weekly life summary generated by the AI Core.

    Attributes:
        week_start: Monday date for the report period.
        week_end: Sunday date for the report period.
        narrative: Full Markdown narrative from Claude.
        highlights: Up to 5 key takeaways.
        mood_summary: Average mood and dominant emotion for the week.
        task_summary: Tasks completed vs created.
        top_memories: The 3 most significant memories of the week.
        recommendations: Actionable suggestions for the coming week.
    """

    week_start: datetime
    week_end: datetime
    narrative: str
    highlights: list[str] = Field(default_factory=list, max_length=5)
    mood_summary: dict = Field(default_factory=dict)
    task_summary: dict = Field(default_factory=dict)
    top_memories: list[str] = Field(default_factory=list)
    recommendations: list[str] = Field(default_factory=list)


class PatternAlert(BaseModel):
    """Detected behavioural or emotional pattern requiring attention.

    Attributes:
        pattern_type: Short machine-readable category.
        severity: ``low`` / ``medium`` / ``high``.
        title: Human-readable alert title.
        description: Detailed explanation from the AI.
        suggested_action: One concrete action the user can take.
        detected_at: When the pattern was identified.
    """

    pattern_type: str
    severity: str = Field(..., pattern=r"^(low|medium|high)$")
    title: str
    description: str
    suggested_action: str
    detected_at: datetime = Field(default_factory=datetime.utcnow)


class ChatMessage(BaseModel):
    """Single message in an AI chat session.

    Attributes:
        role: ``user`` or ``assistant``.
        content: Text content of the message.
    """

    role: str = Field(..., pattern=r"^(user|assistant)$")
    content: str = Field(..., min_length=1)


class ChatRequest(BaseModel):
    """Incoming chat payload sent to ``POST /ai/chat``.

    Attributes:
        message: User's message to Lumina AI.
        include_memories: Whether to inject relevant memories as context.
        conversation_history: Previous turns for multi-turn conversations.
    """

    model_config = ConfigDict(str_strip_whitespace=True)

    message: str = Field(..., min_length=1, max_length=4000)
    include_memories: bool = Field(default=True)
    conversation_history: list[ChatMessage] = Field(default_factory=list)


class ChatResponse(BaseModel):
    """AI chat response returned to the client.

    Attributes:
        reply: Claude's response text.
        memories_used: Number of memory snippets injected as context.
        tokens_used: Input + output tokens consumed.
    """

    reply: str
    memories_used: int = 0
    tokens_used: int = 0
